services:
  bookstore-api-gateway:
    build:
      context: .
      dockerfile: ./apps/bookstore-api-gateway/Dockerfile
      target: development
    command: pnpm run start:dev bookstore-api-gateway
    env_file:
      - ./.env
    depends_on:
      - mongodb-primary
      - rabbitmq
      - auth
      - books
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  books:
    build:
      context: .
      dockerfile: ./apps/books/Dockerfile
      target: development
    command: sh -c './wait-for-it.sh rabbitmq:5672 -- pnpm run start:dev books'
    #command: pnpm run start:dev books
    env_file:
      - ./.env
    depends_on:
      - mongodb-primary
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules    
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '3001:3001'
    env_file:
      - ./.env
    depends_on:
      - mongodb-primary
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  rabbitmq:
    image: rabbitmq:3.13-management
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'  

volumes:
  mongodb_master_data:
    driver: local
